# Generated by Django 5.1.3 on 2024-11-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('confirm_email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('confirm_password', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField()),
                ('telegram', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('preferred_payment_method', models.CharField(default='', max_length=100)),
                ('user_account', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
                ('additional_info', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_to_withdraw', models.IntegerField(default='')),
                ('yesterday', models.IntegerField(default='')),
                ('current_month', models.IntegerField(default='')),
                ('thirty_days', models.IntegerField(default='')),
                ('total', models.IntegerField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default='')),
                ('clicks', models.IntegerField(default='')),
                ('direct_links', models.IntegerField(default='')),
                ('clicks_views', models.IntegerField(default='')),
                ('registrations', models.IntegerField(default='')),
                ('registrations_click_ratios', models.IntegerField(default='')),
                ('registration_with_deposits', models.IntegerField(default='')),
                ('registration_with_deposits_registration_ratio', models.IntegerField(default='')),
                ('total_new_deposit_amount', models.IntegerField(default='')),
                ('overall_commission', models.IntegerField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='app.profile')),
            ],
        ),
    ]
