# Generated by Django 5.1.3 on 2024-11-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='app.profile'),
            preserve_default=False,
        ),
    ]
