# Generated by Django 5.1.3 on 2024-11-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unique_id',
        ),
    ]
