# Generated by Django 5.1.3 on 2024-12-08 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_uerid_id_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_page',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
