# Generated by Django 5.1.3 on 2024-12-08 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_main_page_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
