# Generated by Django 5.1.3 on 2024-12-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_summary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='registration_with_deposits',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='registrations_click_ratios',
        ),
        migrations.AddField(
            model_name='summary',
            name='acccounts_with_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='active_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='average_profit_per_player',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='bonus_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='cpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='new_depositors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='number_of_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='referral_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='sum_of_all_deposits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_rs_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='clicks_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='direct_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='overall_commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='registration_with_deposits_registration_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_new_deposit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
