# Generated by Django 5.1.3 on 2024-12-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_summary_registration_with_deposits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='acccounts_with_deposits',
            new_name='accounts_with_deposits',
        ),
    ]
