# Generated by Django 5.1.3 on 2024-12-08 11:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_acccounts_with_deposits_summary_accounts_with_deposits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('commission_group_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to='app.profile')),
            ],
        ),
    ]
