# Generated by Django 5.1.3 on 2024-12-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to='app.profile'),
        ),
    ]
