# Generated by Django 5.1.3 on 2024-12-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_website_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='payment_history',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='payment_history',
            name='status',
        ),
    ]
