# Generated by Django 5.1.3 on 2024-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_payment_history_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_report',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='full_report',
            name='payout',
        ),
        migrations.RemoveField(
            model_name='full_report',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='full_report',
            name='status',
        ),
        migrations.AddField(
            model_name='full_report',
            name='commission_structure',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
