# Generated by Django 5.1.3 on 2024-12-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_full_report_balance_remove_full_report_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user6', to='app.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='app.website')),
            ],
        ),
    ]
