# Generated by Django 5.1.3 on 2024-12-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_player_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player_report',
            name='website',
        ),
    ]
