# Generated by Django 5.1.3 on 2024-12-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_player_report_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_report',
            name='country',
        ),
    ]
