# Generated by Django 5.1.3 on 2024-12-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_player_report_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user6', to='app.profile'),
            preserve_default=False,
        ),
    ]
