# Generated by Django 5.1.3 on 2024-12-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_player_report_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_history2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('time_interval', models.DateField()),
                ('total_commission', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user7', to='app.profile')),
            ],
        ),
    ]
