# Generated by Django 5.1.3 on 2024-12-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_code',
            name='currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
