# Generated by Django 5.1.3 on 2024-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telegram',
            new_name='messenger',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='confirm_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='messenger_username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
