# Generated by Django 5.1.3 on 2024-12-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_telegram_profile_messenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='messenger_username',
            new_name='messengerusername',
        ),
    ]
