# Generated by Django 5.1.3 on 2024-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_messenger_username_profile_messengerusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
